version: '3.8'
services:
  mongodb:
    image: mongo:latest
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  app:
    depends_on:
      - mongodb
    build: .
    volumes:
      - app:/app/test
volumes:
  mongodb:
  app:
