version: 2
jobs:
  build:
    machine: true
    steps:
      - run:
          name: Pulling image
          command: docker pull lcinder/moon-vie
      - run:
          name: Running container
          command: docker run -t -v $(pwd):/app/test lcinder/moon-vie
