# This workflow uses actions that are not certified by GitHub.
# Estas las proporcionan entidades terceras y las gobiernan
# condiciones de servicio, políticas de privacidad y documentación de soporte
# documentación.

name: Code check

on:
  push:
    paths:
      "README.md"

jobs:
  linter:
    name: Install linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Run linter
        run: gulp lint
  coverage:
    name: Install nyc
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Run coverage tests
        run: gulp test-ts:coverage